# Generated by Django 2.2.4 on 2019-08-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarms_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='sound',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alarms_project.Sound'),
        ),
    ]
