# Generated by Django 2.2.4 on 2019-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms_project', '0002_auto_20190811_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
