# Generated by Django 2.1 on 2019-08-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms_project', '0003_auto_20190811_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
